name: Deploy

on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production (master branch)
        if: github.ref == 'refs/heads/master'
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/html/mexxiss-web/
            sudo git pull https://${{ secrets.PAT }}@github.com/mexxiss/mexxiss-web.git master
            sudo git status

      - name: Deploy to Development (dev branch)
        if: github.ref == 'refs/heads/dev'
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/html/mexxiss-dev/mexxiss-web/
            sudo git pull https://${{ secrets.PAT }}@github.com/mexxiss/mexxiss-web.git dev
            sudo git status
