# name: CI/CD Pipeline for ReactJS (Master and Dev)

# on:
#   push:
#     branches:
#       - master  # Production deployment
#       - dev     # Development deployment

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '18'

#       - name: Install dependencies
#         run: npm install

#       - name: Build project
#         run: npm run build  # This builds the project (output will be in the build/ directory)

#       - name: Upload build artifacts
#         uses: actions/upload-artifact@v3
#         with:
#           name: react-build
#           path: dist/  # Upload the build folder

#   deploy:
#     needs: build
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         environment: [master, dev]  # Handling master (production) and dev (development)

#     steps:
#       - name: Download build artifacts
#         uses: actions/download-artifact@v3
#         with:
#           name: react-build
#           path: ./dist/  # Download the artifacts into the build/ folder

#       # Start the SSH agent and add the private key
#       - name: Start SSH agent
#         uses: webfactory/ssh-agent@v0.5.4
#         with:
#           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#       # Add the server's SSH host key to known_hosts
#       - name: Add server to known hosts
#         run: |
#           mkdir -p ~/.ssh
#           echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
#           chmod 644 ~/.ssh/known_hosts

#       # Remove Old Build Folder on Server (adjust path for environment)
#       - name: Remove Old Build Folder on Server
#         run: |
#           if [ "${{ matrix.environment }}" = "master" ]; then
#             ssh ${{ secrets.USER }}@${{ secrets.SERVER }} "sudo rm -rf /var/www/html/mexxiss-web/dist";
#           else
#             ssh ${{ secrets.USERDEV }}@${{ secrets.SERVERDEV }} "sudo rm -rf /var/www/html/mexxiss-dev/mexxiss-web/dist";
#           fi

#       # Create New Build Folder on Server (adjust path for environment)
#       - name: Create New Build Folder on Server
#         run: |
#           if [ "${{ matrix.environment }}" = "master" ]; then
#             ssh ${{ secrets.USER }}@${{ secrets.SERVER }} "sudo mkdir -p /var/www/html/mexxiss-web/dist";
#           else
#             ssh ${{ secrets.USERDEV }}@${{ secrets.SERVERDEV }} "sudo mkdir -p /var/www/html/mexxiss-dev/mexxiss-web/dist";
#           fi

#       # Set Folder Permissions (adjust path for environment)
#       - name: Set Folder Permissions
#         run: |
#           if [ "${{ matrix.environment }}" = "master" ]; then
#             ssh ${{ secrets.USER }}@${{ secrets.SERVER }} "sudo chmod 755 /var/www/html/mexxiss-web/dist";
#           else
#             ssh ${{ secrets.USERDEV }}@${{ secrets.SERVERDEV }} "sudo chmod 755 /var/www/html/mexxiss-dev/mexxiss-web/dist";
#           fi

#       # Deploy artifacts using SCP (adjust path for environment)
#       - name: Deploy artifacts using SCP
#         run: |
#           if [ "${{ matrix.environment }}" = "master" ]; then
#             scp -r dist/* ${{ secrets.USER }}@${{ secrets.SERVER }}:/var/www/html/mexxiss-web/dist;
#           else
#             scp -r dist/* ${{ secrets.USERDEV }}@${{ secrets.SERVERDEV }}:/var/www/html/mexxiss-dev/mexxiss-web/dist;
#           fi